name: AestheticConcepts.ns
favicon: null
layout_spectrum: 0.015360471094027162
typography_spectrum: 0.9132939255796373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5201869762968272
  lightness: 0.9545635913964361
  saturation: 0.8477529443334788
  rhythmicContrast: 0.15549050853587687
purpose: []
